# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_parsers')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_parsers')
    _parsers = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_parsers', [dirname(__file__)])
        except ImportError:
            import _parsers
            return _parsers
        try:
            _mod = imp.load_module('_parsers', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _parsers = swig_import_helper()
    del swig_import_helper
else:
    import _parsers
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _parsers.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _parsers.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _parsers.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _parsers.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _parsers.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _parsers.SwigPyIterator_equal(self, x)

    def copy(self):
        return _parsers.SwigPyIterator_copy(self)

    def next(self):
        return _parsers.SwigPyIterator_next(self)

    def __next__(self):
        return _parsers.SwigPyIterator___next__(self)

    def previous(self):
        return _parsers.SwigPyIterator_previous(self)

    def advance(self, n):
        return _parsers.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _parsers.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _parsers.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _parsers.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _parsers.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _parsers.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _parsers.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _parsers.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vector_double(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_double, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_double, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _parsers.vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _parsers.vector_double___nonzero__(self)

    def __bool__(self):
        return _parsers.vector_double___bool__(self)

    def __len__(self):
        return _parsers.vector_double___len__(self)

    def __getslice__(self, i, j):
        return _parsers.vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _parsers.vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _parsers.vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _parsers.vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _parsers.vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _parsers.vector_double___setitem__(self, *args)

    def pop(self):
        return _parsers.vector_double_pop(self)

    def append(self, x):
        return _parsers.vector_double_append(self, x)

    def empty(self):
        return _parsers.vector_double_empty(self)

    def size(self):
        return _parsers.vector_double_size(self)

    def swap(self, v):
        return _parsers.vector_double_swap(self, v)

    def begin(self):
        return _parsers.vector_double_begin(self)

    def end(self):
        return _parsers.vector_double_end(self)

    def rbegin(self):
        return _parsers.vector_double_rbegin(self)

    def rend(self):
        return _parsers.vector_double_rend(self)

    def clear(self):
        return _parsers.vector_double_clear(self)

    def get_allocator(self):
        return _parsers.vector_double_get_allocator(self)

    def pop_back(self):
        return _parsers.vector_double_pop_back(self)

    def erase(self, *args):
        return _parsers.vector_double_erase(self, *args)

    def __init__(self, *args):
        this = _parsers.new_vector_double(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _parsers.vector_double_push_back(self, x)

    def front(self):
        return _parsers.vector_double_front(self)

    def back(self):
        return _parsers.vector_double_back(self)

    def assign(self, n, x):
        return _parsers.vector_double_assign(self, n, x)

    def resize(self, *args):
        return _parsers.vector_double_resize(self, *args)

    def insert(self, *args):
        return _parsers.vector_double_insert(self, *args)

    def reserve(self, n):
        return _parsers.vector_double_reserve(self, n)

    def capacity(self):
        return _parsers.vector_double_capacity(self)
    __swig_destroy__ = _parsers.delete_vector_double
    __del__ = lambda self: None
vector_double_swigregister = _parsers.vector_double_swigregister
vector_double_swigregister(vector_double)

class vector_uchar(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_uchar, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_uchar, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _parsers.vector_uchar_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _parsers.vector_uchar___nonzero__(self)

    def __bool__(self):
        return _parsers.vector_uchar___bool__(self)

    def __len__(self):
        return _parsers.vector_uchar___len__(self)

    def __getslice__(self, i, j):
        return _parsers.vector_uchar___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _parsers.vector_uchar___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _parsers.vector_uchar___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _parsers.vector_uchar___delitem__(self, *args)

    def __getitem__(self, *args):
        return _parsers.vector_uchar___getitem__(self, *args)

    def __setitem__(self, *args):
        return _parsers.vector_uchar___setitem__(self, *args)

    def pop(self):
        return _parsers.vector_uchar_pop(self)

    def append(self, x):
        return _parsers.vector_uchar_append(self, x)

    def empty(self):
        return _parsers.vector_uchar_empty(self)

    def size(self):
        return _parsers.vector_uchar_size(self)

    def swap(self, v):
        return _parsers.vector_uchar_swap(self, v)

    def begin(self):
        return _parsers.vector_uchar_begin(self)

    def end(self):
        return _parsers.vector_uchar_end(self)

    def rbegin(self):
        return _parsers.vector_uchar_rbegin(self)

    def rend(self):
        return _parsers.vector_uchar_rend(self)

    def clear(self):
        return _parsers.vector_uchar_clear(self)

    def get_allocator(self):
        return _parsers.vector_uchar_get_allocator(self)

    def pop_back(self):
        return _parsers.vector_uchar_pop_back(self)

    def erase(self, *args):
        return _parsers.vector_uchar_erase(self, *args)

    def __init__(self, *args):
        this = _parsers.new_vector_uchar(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _parsers.vector_uchar_push_back(self, x)

    def front(self):
        return _parsers.vector_uchar_front(self)

    def back(self):
        return _parsers.vector_uchar_back(self)

    def assign(self, n, x):
        return _parsers.vector_uchar_assign(self, n, x)

    def resize(self, *args):
        return _parsers.vector_uchar_resize(self, *args)

    def insert(self, *args):
        return _parsers.vector_uchar_insert(self, *args)

    def reserve(self, n):
        return _parsers.vector_uchar_reserve(self, n)

    def capacity(self):
        return _parsers.vector_uchar_capacity(self)
    __swig_destroy__ = _parsers.delete_vector_uchar
    __del__ = lambda self: None
vector_uchar_swigregister = _parsers.vector_uchar_swigregister
vector_uchar_swigregister(vector_uchar)

class vector_vector_double(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_vector_double, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_vector_double, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _parsers.vector_vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _parsers.vector_vector_double___nonzero__(self)

    def __bool__(self):
        return _parsers.vector_vector_double___bool__(self)

    def __len__(self):
        return _parsers.vector_vector_double___len__(self)

    def __getslice__(self, i, j):
        return _parsers.vector_vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _parsers.vector_vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _parsers.vector_vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _parsers.vector_vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _parsers.vector_vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _parsers.vector_vector_double___setitem__(self, *args)

    def pop(self):
        return _parsers.vector_vector_double_pop(self)

    def append(self, x):
        return _parsers.vector_vector_double_append(self, x)

    def empty(self):
        return _parsers.vector_vector_double_empty(self)

    def size(self):
        return _parsers.vector_vector_double_size(self)

    def swap(self, v):
        return _parsers.vector_vector_double_swap(self, v)

    def begin(self):
        return _parsers.vector_vector_double_begin(self)

    def end(self):
        return _parsers.vector_vector_double_end(self)

    def rbegin(self):
        return _parsers.vector_vector_double_rbegin(self)

    def rend(self):
        return _parsers.vector_vector_double_rend(self)

    def clear(self):
        return _parsers.vector_vector_double_clear(self)

    def get_allocator(self):
        return _parsers.vector_vector_double_get_allocator(self)

    def pop_back(self):
        return _parsers.vector_vector_double_pop_back(self)

    def erase(self, *args):
        return _parsers.vector_vector_double_erase(self, *args)

    def __init__(self, *args):
        this = _parsers.new_vector_vector_double(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _parsers.vector_vector_double_push_back(self, x)

    def front(self):
        return _parsers.vector_vector_double_front(self)

    def back(self):
        return _parsers.vector_vector_double_back(self)

    def assign(self, n, x):
        return _parsers.vector_vector_double_assign(self, n, x)

    def resize(self, *args):
        return _parsers.vector_vector_double_resize(self, *args)

    def insert(self, *args):
        return _parsers.vector_vector_double_insert(self, *args)

    def reserve(self, n):
        return _parsers.vector_vector_double_reserve(self, n)

    def capacity(self):
        return _parsers.vector_vector_double_capacity(self)
    __swig_destroy__ = _parsers.delete_vector_vector_double
    __del__ = lambda self: None
vector_vector_double_swigregister = _parsers.vector_vector_double_swigregister
vector_vector_double_swigregister(vector_vector_double)


def pfm(filename):
    return _parsers.pfm(filename)
pfm = _parsers.pfm

def pfm_to_log_odds(filename, bg, pseudocount, log_base=-1):
    return _parsers.pfm_to_log_odds(filename, bg, pseudocount, log_base)
pfm_to_log_odds = _parsers.pfm_to_log_odds

def adm_1o_terms(filename, a=4):
    return _parsers.adm_1o_terms(filename, a)
adm_1o_terms = _parsers.adm_1o_terms

def adm_0o_terms(filename, a=4):
    return _parsers.adm_0o_terms(filename, a)
adm_0o_terms = _parsers.adm_0o_terms

def adm_to_log_odds(filename, bg, pseudocount, a=4, log_base=-1):
    return _parsers.adm_to_log_odds(filename, bg, pseudocount, a, log_base)
adm_to_log_odds = _parsers.adm_to_log_odds
# This file is compatible with both classic and new-style classes.


