# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_tools')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_tools')
    _tools = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tools', [dirname(__file__)])
        except ImportError:
            import _tools
            return _tools
        try:
            _mod = imp.load_module('_tools', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _tools = swig_import_helper()
    del swig_import_helper
else:
    import _tools
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _tools.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _tools.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _tools.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _tools.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _tools.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _tools.SwigPyIterator_equal(self, x)

    def copy(self):
        return _tools.SwigPyIterator_copy(self)

    def next(self):
        return _tools.SwigPyIterator_next(self)

    def __next__(self):
        return _tools.SwigPyIterator___next__(self)

    def previous(self):
        return _tools.SwigPyIterator_previous(self)

    def advance(self, n):
        return _tools.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _tools.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _tools.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _tools.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _tools.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _tools.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _tools.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _tools.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vector_double(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_double, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_double, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _tools.vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tools.vector_double___nonzero__(self)

    def __bool__(self):
        return _tools.vector_double___bool__(self)

    def __len__(self):
        return _tools.vector_double___len__(self)

    def __getslice__(self, i, j):
        return _tools.vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _tools.vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _tools.vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _tools.vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _tools.vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _tools.vector_double___setitem__(self, *args)

    def pop(self):
        return _tools.vector_double_pop(self)

    def append(self, x):
        return _tools.vector_double_append(self, x)

    def empty(self):
        return _tools.vector_double_empty(self)

    def size(self):
        return _tools.vector_double_size(self)

    def swap(self, v):
        return _tools.vector_double_swap(self, v)

    def begin(self):
        return _tools.vector_double_begin(self)

    def end(self):
        return _tools.vector_double_end(self)

    def rbegin(self):
        return _tools.vector_double_rbegin(self)

    def rend(self):
        return _tools.vector_double_rend(self)

    def clear(self):
        return _tools.vector_double_clear(self)

    def get_allocator(self):
        return _tools.vector_double_get_allocator(self)

    def pop_back(self):
        return _tools.vector_double_pop_back(self)

    def erase(self, *args):
        return _tools.vector_double_erase(self, *args)

    def __init__(self, *args):
        this = _tools.new_vector_double(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _tools.vector_double_push_back(self, x)

    def front(self):
        return _tools.vector_double_front(self)

    def back(self):
        return _tools.vector_double_back(self)

    def assign(self, n, x):
        return _tools.vector_double_assign(self, n, x)

    def resize(self, *args):
        return _tools.vector_double_resize(self, *args)

    def insert(self, *args):
        return _tools.vector_double_insert(self, *args)

    def reserve(self, n):
        return _tools.vector_double_reserve(self, n)

    def capacity(self):
        return _tools.vector_double_capacity(self)
    __swig_destroy__ = _tools.delete_vector_double
    __del__ = lambda self: None
vector_double_swigregister = _tools.vector_double_swigregister
vector_double_swigregister(vector_double)

class vector_uchar(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_uchar, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_uchar, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _tools.vector_uchar_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tools.vector_uchar___nonzero__(self)

    def __bool__(self):
        return _tools.vector_uchar___bool__(self)

    def __len__(self):
        return _tools.vector_uchar___len__(self)

    def __getslice__(self, i, j):
        return _tools.vector_uchar___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _tools.vector_uchar___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _tools.vector_uchar___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _tools.vector_uchar___delitem__(self, *args)

    def __getitem__(self, *args):
        return _tools.vector_uchar___getitem__(self, *args)

    def __setitem__(self, *args):
        return _tools.vector_uchar___setitem__(self, *args)

    def pop(self):
        return _tools.vector_uchar_pop(self)

    def append(self, x):
        return _tools.vector_uchar_append(self, x)

    def empty(self):
        return _tools.vector_uchar_empty(self)

    def size(self):
        return _tools.vector_uchar_size(self)

    def swap(self, v):
        return _tools.vector_uchar_swap(self, v)

    def begin(self):
        return _tools.vector_uchar_begin(self)

    def end(self):
        return _tools.vector_uchar_end(self)

    def rbegin(self):
        return _tools.vector_uchar_rbegin(self)

    def rend(self):
        return _tools.vector_uchar_rend(self)

    def clear(self):
        return _tools.vector_uchar_clear(self)

    def get_allocator(self):
        return _tools.vector_uchar_get_allocator(self)

    def pop_back(self):
        return _tools.vector_uchar_pop_back(self)

    def erase(self, *args):
        return _tools.vector_uchar_erase(self, *args)

    def __init__(self, *args):
        this = _tools.new_vector_uchar(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _tools.vector_uchar_push_back(self, x)

    def front(self):
        return _tools.vector_uchar_front(self)

    def back(self):
        return _tools.vector_uchar_back(self)

    def assign(self, n, x):
        return _tools.vector_uchar_assign(self, n, x)

    def resize(self, *args):
        return _tools.vector_uchar_resize(self, *args)

    def insert(self, *args):
        return _tools.vector_uchar_insert(self, *args)

    def reserve(self, n):
        return _tools.vector_uchar_reserve(self, n)

    def capacity(self):
        return _tools.vector_uchar_capacity(self)
    __swig_destroy__ = _tools.delete_vector_uchar
    __del__ = lambda self: None
vector_uchar_swigregister = _tools.vector_uchar_swigregister
vector_uchar_swigregister(vector_uchar)

class vector_vector_double(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_vector_double, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_vector_double, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _tools.vector_vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tools.vector_vector_double___nonzero__(self)

    def __bool__(self):
        return _tools.vector_vector_double___bool__(self)

    def __len__(self):
        return _tools.vector_vector_double___len__(self)

    def __getslice__(self, i, j):
        return _tools.vector_vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _tools.vector_vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _tools.vector_vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _tools.vector_vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _tools.vector_vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _tools.vector_vector_double___setitem__(self, *args)

    def pop(self):
        return _tools.vector_vector_double_pop(self)

    def append(self, x):
        return _tools.vector_vector_double_append(self, x)

    def empty(self):
        return _tools.vector_vector_double_empty(self)

    def size(self):
        return _tools.vector_vector_double_size(self)

    def swap(self, v):
        return _tools.vector_vector_double_swap(self, v)

    def begin(self):
        return _tools.vector_vector_double_begin(self)

    def end(self):
        return _tools.vector_vector_double_end(self)

    def rbegin(self):
        return _tools.vector_vector_double_rbegin(self)

    def rend(self):
        return _tools.vector_vector_double_rend(self)

    def clear(self):
        return _tools.vector_vector_double_clear(self)

    def get_allocator(self):
        return _tools.vector_vector_double_get_allocator(self)

    def pop_back(self):
        return _tools.vector_vector_double_pop_back(self)

    def erase(self, *args):
        return _tools.vector_vector_double_erase(self, *args)

    def __init__(self, *args):
        this = _tools.new_vector_vector_double(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _tools.vector_vector_double_push_back(self, x)

    def front(self):
        return _tools.vector_vector_double_front(self)

    def back(self):
        return _tools.vector_vector_double_back(self)

    def assign(self, n, x):
        return _tools.vector_vector_double_assign(self, n, x)

    def resize(self, *args):
        return _tools.vector_vector_double_resize(self, *args)

    def insert(self, *args):
        return _tools.vector_vector_double_insert(self, *args)

    def reserve(self, n):
        return _tools.vector_vector_double_reserve(self, n)

    def capacity(self):
        return _tools.vector_vector_double_capacity(self)
    __swig_destroy__ = _tools.delete_vector_vector_double
    __del__ = lambda self: None
vector_vector_double_swigregister = _tools.vector_vector_double_swigregister
vector_vector_double_swigregister(vector_vector_double)

class vector_variant(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_variant, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_variant, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _tools.vector_variant_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tools.vector_variant___nonzero__(self)

    def __bool__(self):
        return _tools.vector_variant___bool__(self)

    def __len__(self):
        return _tools.vector_variant___len__(self)

    def __getslice__(self, i, j):
        return _tools.vector_variant___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _tools.vector_variant___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _tools.vector_variant___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _tools.vector_variant___delitem__(self, *args)

    def __getitem__(self, *args):
        return _tools.vector_variant___getitem__(self, *args)

    def __setitem__(self, *args):
        return _tools.vector_variant___setitem__(self, *args)

    def pop(self):
        return _tools.vector_variant_pop(self)

    def append(self, x):
        return _tools.vector_variant_append(self, x)

    def empty(self):
        return _tools.vector_variant_empty(self)

    def size(self):
        return _tools.vector_variant_size(self)

    def swap(self, v):
        return _tools.vector_variant_swap(self, v)

    def begin(self):
        return _tools.vector_variant_begin(self)

    def end(self):
        return _tools.vector_variant_end(self)

    def rbegin(self):
        return _tools.vector_variant_rbegin(self)

    def rend(self):
        return _tools.vector_variant_rend(self)

    def clear(self):
        return _tools.vector_variant_clear(self)

    def get_allocator(self):
        return _tools.vector_variant_get_allocator(self)

    def pop_back(self):
        return _tools.vector_variant_pop_back(self)

    def erase(self, *args):
        return _tools.vector_variant_erase(self, *args)

    def __init__(self, *args):
        this = _tools.new_vector_variant(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _tools.vector_variant_push_back(self, x)

    def front(self):
        return _tools.vector_variant_front(self)

    def back(self):
        return _tools.vector_variant_back(self)

    def assign(self, n, x):
        return _tools.vector_variant_assign(self, n, x)

    def resize(self, *args):
        return _tools.vector_variant_resize(self, *args)

    def insert(self, *args):
        return _tools.vector_variant_insert(self, *args)

    def reserve(self, n):
        return _tools.vector_variant_reserve(self, n)

    def capacity(self):
        return _tools.vector_variant_capacity(self)
    __swig_destroy__ = _tools.delete_vector_variant
    __del__ = lambda self: None
vector_variant_swigregister = _tools.vector_variant_swigregister
vector_variant_swigregister(vector_variant)

class match(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, match, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, match, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pos"] = _tools.match_pos_set
    __swig_getmethods__["pos"] = _tools.match_pos_get
    if _newclass:
        pos = _swig_property(_tools.match_pos_get, _tools.match_pos_set)
    __swig_setmethods__["score"] = _tools.match_score_set
    __swig_getmethods__["score"] = _tools.match_score_get
    if _newclass:
        score = _swig_property(_tools.match_score_get, _tools.match_score_set)

    def __init__(self):
        this = _tools.new_match()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _tools.delete_match
    __del__ = lambda self: None
match_swigregister = _tools.match_swigregister
match_swigregister(match)

class variant(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, variant, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, variant, name)
    __repr__ = _swig_repr
    __swig_setmethods__["start_pos"] = _tools.variant_start_pos_set
    __swig_getmethods__["start_pos"] = _tools.variant_start_pos_get
    if _newclass:
        start_pos = _swig_property(_tools.variant_start_pos_get, _tools.variant_start_pos_set)
    __swig_setmethods__["end_pos"] = _tools.variant_end_pos_set
    __swig_getmethods__["end_pos"] = _tools.variant_end_pos_get
    if _newclass:
        end_pos = _swig_property(_tools.variant_end_pos_get, _tools.variant_end_pos_set)
    __swig_setmethods__["modified_seq"] = _tools.variant_modified_seq_set
    __swig_getmethods__["modified_seq"] = _tools.variant_modified_seq_get
    if _newclass:
        modified_seq = _swig_property(_tools.variant_modified_seq_get, _tools.variant_modified_seq_set)

    def __lt__(self, rhs):
        return _tools.variant___lt__(self, rhs)

    def __init__(self, *args):
        this = _tools.new_variant(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _tools.delete_variant
    __del__ = lambda self: None
variant_swigregister = _tools.variant_swigregister
variant_swigregister(variant)

class match_with_variant(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, match_with_variant, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, match_with_variant, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pos"] = _tools.match_with_variant_pos_set
    __swig_getmethods__["pos"] = _tools.match_with_variant_pos_get
    if _newclass:
        pos = _swig_property(_tools.match_with_variant_pos_get, _tools.match_with_variant_pos_set)
    __swig_setmethods__["score"] = _tools.match_with_variant_score_set
    __swig_getmethods__["score"] = _tools.match_with_variant_score_get
    if _newclass:
        score = _swig_property(_tools.match_with_variant_score_get, _tools.match_with_variant_score_set)
    __swig_setmethods__["variants"] = _tools.match_with_variant_variants_set
    __swig_getmethods__["variants"] = _tools.match_with_variant_variants_get
    if _newclass:
        variants = _swig_property(_tools.match_with_variant_variants_get, _tools.match_with_variant_variants_set)

    def __init__(self):
        this = _tools.new_match_with_variant()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _tools.delete_match_with_variant
    __del__ = lambda self: None
match_with_variant_swigregister = _tools.match_with_variant_swigregister
match_with_variant_swigregister(match_with_variant)


def flat_bg(alphabet_size):
    return _tools.flat_bg(alphabet_size)
flat_bg = _tools.flat_bg

def bg_from_sequence_dna(seq, ps):
    return _tools.bg_from_sequence_dna(seq, ps)
bg_from_sequence_dna = _tools.bg_from_sequence_dna

def snp_variants(seq):
    return _tools.snp_variants(seq)
snp_variants = _tools.snp_variants

def min_delta(mat):
    return _tools.min_delta(mat)
min_delta = _tools.min_delta

def max_score(*args):
    return _tools.max_score(*args)
max_score = _tools.max_score

def min_score(*args):
    return _tools.min_score(*args)
min_score = _tools.min_score

def threshold_from_p(*args):
    return _tools.threshold_from_p(*args)
threshold_from_p = _tools.threshold_from_p

def threshold_from_p_with_precision(*args):
    return _tools.threshold_from_p_with_precision(*args)
threshold_from_p_with_precision = _tools.threshold_from_p_with_precision

def reverse_complement(*args):
    return _tools.reverse_complement(*args)
reverse_complement = _tools.reverse_complement

def log_odds(*args):
    return _tools.log_odds(*args)
log_odds = _tools.log_odds
# This file is compatible with both classic and new-style classes.

cvar = _tools.cvar
DEFAULT_DP_PRECISION = cvar.DEFAULT_DP_PRECISION

